package com.ipensee.core;

import java.text.SimpleDateFormat;
import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_name
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.birthday
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	private Date birthday;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_name
	 * @return  the value of user.user_name
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_name
	 * @param userName  the value for user.user_name
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.birthday
	 * @return  the value of user.birthday
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.birthday
	 * @param birthday  the value for user.birthday
	 * @mbggenerated  Wed Jun 19 13:35:14 CST 2013
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}
	
	@Override
	public String toString() {
		return "id:" + id + "\t\tname:" + userName + "\tbirthday:" + new SimpleDateFormat("yyyy-MM-dd").format(birthday);
	}
}
